//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entitites 
{
    using System.Collections.Generic;
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietHoaDon {
        public int IdHoaDon { get; set; }
        public int IdMonAn { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }

    }
}