//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entitites 
{
    using System.Collections.Generic;
    using System;
    using System.ComponentModel.DataAnnotations;
    public class ChiTietHoaDon {

        public int Id { get; set; }
        [Display(Name = "Mã hóa đơn")]
        public int IdHoaDon { get; set; }

        [Display(Name = "Món ăn")]
        public int IdMonAn { get; set; }

        [Range(1,10)]
        [Display(Name = "Số lượng")]
        public Nullable<int> SoLuong { get; set; }

        [Range(1, 10)]
        [Display(Name = "Đơn giá")]
        public Nullable<int> DonGia { get; set; }

    }
}