//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entitites {
    using System.Collections.Generic;
    using System;

    public partial class HoaDon {
       

        public int Id { get; set; }
        public int IdBanAn { get; set; }
        public int IdUser { get; set; }
        public System.DateTime ThoiGianLap { get; set; }
        public Nullable<int> ThanhTien { get; set; }

        public virtual BanAn BanAn { get; set; }

    }
}