using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entitites {
    using System.Collections.Generic;
    using System;
    using System.ComponentModel.DataAnnotations;
    using ApplicationCore.Interfaces;

    public class HoaDon :IAggregateRoot{
       
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Display(Name="Bàn số")]
        public int IdBanAn { get; set; }
        
        [Display(Name = "Nhân viên")]
        public int IdUser { get; set; }

        [Display(Name = "Thời gian lập")]
        public System.DateTime ThoiGianLap { get; set; }

        [Display(Name = "Thời gian thanh toán")]
        public Nullable<System.DateTime> ThoiGianThanhToan { get; set; }

        [Display(Name = "Thành tiền")]        
        public Nullable<int> ThanhTien { get; set; }

    }
}