//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entitites 
{
    using System.Collections.Generic;
    using System;

    public partial class KhachHang {
     
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DiaChi { get; set; }


    }
}