//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entitites 
{
    using System.Collections.Generic;
    using System;
    using ApplicationCore.Interfaces;

    public class KhachHang :IAggregateRoot{
     
        public int Id { get; set; }
        public string Ten { get; set; }
        public Nullable<int> SDT { get; set; }
        public DiaChiNha DiaChi;

        public class DiaChiNha
        {
            public string SoNha,TenDuong,Phuong,Quan,ThanhPho;

            public DiaChiNha(string SoNha,string TenDuong,string Phuong,string Quan,string ThanhPho)
            {
                this.SoNha = SoNha;
                this.TenDuong = TenDuong;
                this.Phuong = Phuong;
                this.Quan = Quan;
                this.ThanhPho = ThanhPho;
            }
        }
    }
}