//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entities
 {
    using System.Collections.Generic;
    using System;
    using ApplicationCore.Interfaces;

    public  class PhieuDatBan:IAggregateRoot {
        public int Id { get; set; }
        public int IdBanAn { get; set; }
        public int IdKhachHang { get; set; }
        public DateTime ThoiGianDat { get; set; }
        public string TrangThai{ get; set; }
        public string GhiChu { get; set; }
        ///////////////////////////////////////////////////////
        public virtual BanAn BanAn { get; set; }
        public virtual KhachHang KhachHang { get; set; }

    }
}