//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.DTOs.SaveDTOs
{
    using System.Collections.Generic;
    using System;
    using System.ComponentModel.DataAnnotations;
    using ApplicationCore.Entities;

    public class SaveNguoiDungDTO
    {
        public SaveNguoiDungDTO()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.PhieuDatBans = new HashSet<PhieuDatBan>();
        }
        public int Id { get; set; }
        [Display(Name = "Tên")]
        [Required]
        public string Ten { get; set; }

        [Display(Name = "Tên đăng nhập")]
        [Required]
        public string TenDangNhap { get; set; }

        [Display(Name = "Mật khẩu")]
        [Required]
        public string MatKhau { get; set; }

        [Display(Name = "Vai trò")]
        [Required]
        public string Role { get; set; }

        [Display(Name = "Trạng thái")]
        [Required]
        public int TrangThai { get; set; }

        ///////////////////////////////////////////
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<PhieuDatBan> PhieuDatBans { get; set; }
    }
}