//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.DTOs.SaveDTOs
 {
    using System.Collections.Generic;
    using System;
    using ApplicationCore.Interfaces;
    using System.ComponentModel.DataAnnotations;
    using ApplicationCore.Entities;

    public  class SavePhieuDatBanDTO {
        public int Id { get; set; }

        [Display(Name = "Bàn ăn")]
        [Required]
        public int IdBanAn { get; set; }

        [Display(Name = "Tên khách hàng")]
        [Required]
        public int IdKhachHang { get; set; }

        [Display(Name = "Thời gian đặt")]
        [Required]
        public DateTime ThoiGianDat { get; set; }

        [Display(Name = "Trạng thái")]
        [Required]
        public string TrangThai{ get; set; }

        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }

        public virtual KhachHang KhachHang { get; set; }

    }
}