using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entities {
    using System.Collections.Generic;
    using System;
    using ApplicationCore.Interfaces;
    using System.ComponentModel.DataAnnotations;

    public partial class BanAn :IAggregateRoot {

        public BanAn()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.PhieuDatBans = new HashSet<PhieuDatBan>();
        }
        public int Id { get; set; }

        public string LoaiBanAn { get; set; }

        public string TrangThai { get; set; }

        public string GhiChu { get; set; }

        ///////////////////////////////////////////////////
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual ICollection<PhieuDatBan> PhieuDatBans { get; set; }
    }
}