using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entities {
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System;
    using ApplicationCore.Interfaces;

    public class HoaDon : IAggregateRoot {

        public HoaDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }

        public int Id { get; set; }

        public int IdBanAn { get; set; }

        public int IdUser { get; set; }

        public System.DateTime ThoiGianLap { get; set; }

        public Nullable<System.DateTime> ThoiGianThanhToan { get; set; }

        public int ThanhTien { get; set; }

        public string TrangThai { get; set; }

        ///////////////////////////////////////////
        public virtual BanAn BanAn { get; set; }
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}