//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.Entities
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    using System;
    using ApplicationCore.Interfaces;

    public class ThucDon : IAggregateRoot
    {

        public ThucDon()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }
        public int Id { get; set; }

        public int IdLoaiMonAn { get; set; }

        public string Ten { get; set; }

        public int Gia { get; set; }

        /////////////////////////////////////////////////////////////
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual LoaiMonAn LoaiMonAn { get; set; }
    }
}