//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCore.DTOs.SaveDTOs {
    using System.Collections.Generic;
    using System;
    using ApplicationCore.Interfaces;
    using System.ComponentModel.DataAnnotations;
    using ApplicationCore.Entities;

    public class SaveKhachHangDTO  {

        public SaveKhachHangDTO()
        {
            this.PhieuDatBans = new HashSet<PhieuDatBan>();
        }
        public int Id { get; set; }
        
        [Display(Name = "Tên khách hàng")]
        [Required]
        public string Ten { get; set; }

        [Display(Name = "Số điện thoại")]
        [Required]
        public string SDT { get; set; }

        [Display(Name = "Địa chỉ")]
        // [Required]
        public string DiaChi { get; set; }

        ///////////////////////////////////////
        public virtual ICollection<PhieuDatBan> PhieuDatBans { get; set; }
    }

}